// File generated by FlutterFire CLI / configured for geoattendance-d9591
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb7Z_ynRlBMKyGIYZDwgxaNfy0NnovPQk',
    appId: '1:957382489886:web:53bb83c9f7d9468c177b0f',
    messagingSenderId: '957382489886',
    projectId: 'geoattendance-d9591',
    authDomain: 'geoattendance-d9591.firebaseapp.com',
    databaseURL: 'https://geoattendance-d9591-default-rtdb.firebaseio.com',
    storageBucket: 'geoattendance-d9591.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb7Z_ynRlBMKyGIYZDwgxaNfy0NnovPQk',
    appId: '1:957382489886:android:53bb83c9f7d9468c177b0f',
    messagingSenderId: '957382489886',
    projectId: 'geoattendance-d9591',
    databaseURL: 'https://geoattendance-d9591-default-rtdb.firebaseio.com',
    storageBucket: 'geoattendance-d9591.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb7Z_ynRlBMKyGIYZDwgxaNfy0NnovPQk',
    appId: '1:957382489886:ios:53bb83c9f7d9468c177b0f',
    messagingSenderId: '957382489886',
    projectId: 'geoattendance-d9591',
    databaseURL: 'https://geoattendance-d9591-default-rtdb.firebaseio.com',
    storageBucket: 'geoattendance-d9591.firebasestorage.app',
    iosBundleId: 'com.nmims.geoattendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb7Z_ynRlBMKyGIYZDwgxaNfy0NnovPQk',
    appId: '1:957382489886:ios:53bb83c9f7d9468c177b0f',
    messagingSenderId: '957382489886',
    projectId: 'geoattendance-d9591',
    databaseURL: 'https://geoattendance-d9591-default-rtdb.firebaseio.com',
    storageBucket: 'geoattendance-d9591.firebasestorage.app',
    iosBundleId: 'com.nmims.geoattendance',
  );
}
